
server:
  port: 9011

spring:
  application:
    name: sm-dictionary-service

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/school_meals?currentSchema=sm_dictionary}
    username: ${DATASOURCE_USER:sm_user}
    password: ${DATASOURCE_PASSWORD:P@ssw0rd}
  liquibase:
    change-log: classpath:db-migration/changelog.xml

security:
  oauth2:
    resource:
      token-info-uri: ${webservices.auth-service-url}/api/v1/oauth/check_token
      jwt.key-uri: ${webservices.auth-service-url}/api/v1/oauth/token_key
    client:
      client-id: web-app
      client-secret: 123456

webservices:
  auth-service-url: ${SM_AUTH_SERVICE_URL:http://localhost:9001}
