security:
  oauth2:
    resource:
      filter-order: 3
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/school_meals?currentSchema=sm_auth}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  liquibase:
    change-log: classpath:db-migration/changelog.xml
server:
  port: 9001
