server:
  port: 7001
spring:
  application:
    name: sm-auth-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/school_meals?currentSchema=sm_auth}
    username: ${DATASOURCE_USER:sm_user}
    password: ${DATASOURCE_PASSWORD:P@ssw0rd}
  liquibase:
    change-log: classpath:db-migration/changelog.xml

jwt:
  private-key: >
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEA0rsn7zFS7uUhYs/N91lraHiZxjRZXjlKu8ZXHNKeXAOrnKCb
    4nxyM5cK+03Iwu+k+bEewQqKqXU/DiDrOT6U6YL9oTblpXDb6lyP3ksHS0KZxorV
    n34IcdSNS8RuSD0RFb2wFE6/lhQaBaneqiSB121a7xIRduAQBtRCqHjjSl/3KOVi
    AiwWoK7q/UFcKVUPjnk1NqgDaKB1zeEtIxC34O2c8ILg8kvHnGlcq4T4u6ISHiG+
    paxgLbDR8wuIb8nHzGb4lPCXsO84QpIwgRwOFltaqsw2QudLEjdQjKMSaU7t0tqo
    /riGSVX/SPtSxmQb2aewD+dMebYQxxf1DXk7MQIDAQABAoIBAH0v6+BgB+mduwCt
    fKlFuNYeVxP1Q2YDWQ9GG7gmsybsk0V/8DtTPLDDOSXjprGPlg0zmJaLgaZ73ZKy
    IasnL2WtiKj+KNzot+x5QoqHPfUKwrm8/n06bR/aanopXm6RwJWO04ys34nztSXK
    LVocR/pHn67IqBFbuImmDVdyQWyLkzjUhc45b4usq+xVcqKXMORsFubeV+waiz9y
    AdMCHSslFOf4iJomO1e1LiRgHMm8CA9JNihtbD+obrWPbLAvT2xc8EhR2LkO7c1I
    bxgK6ONObx2k0HRgJVngsBbeCORIwGoYcQVJ3NXdPEI2w2NTKzw4UYAzDMHdlCei
    IQoxxgECgYEA+7VKGaUz3sUPOmgJK8qj9QjkM5TKrG9VZF3hRwfro/ErcfmL+FRV
    tSs1PcTKbUovButHPaFJzg+jp4AMP9uXcRJdS5Ej6pMj0WYGDntDAuXrnWRB+Dql
    F2rqLCnNxmaqIh+bcUcM/yZocKIJDsZ6sySJ3BNLVhv8mskbgiV9YtECgYEA1lMA
    N6nO4VMuzlR4FsB7dwOPa/adAeX6bNQ7ugSUFtP5y51QByEEPtA6UoIIBzMisZf2
    Lvi/1O+hlwJTrVfGen/ARukMyT1wCZ1Ir8JOKJl7oaiKS1VCV3aGV3yFv9PKL3aQ
    Q+dIg8PaksCSDpf74dfvqf4rqVKdzE5V7CXYqmECgYAK6FhFtDsDNFbsmQWMuENS
    owgAlDoULt7scoUIpvc3K4ROdBn0sPLl3vF3s8dx5P0Ut61mpk6kd1kIMSxWuBVf
    +QPB+pAr4iRzNpCcoArPXVdQgr+5GhF9akyrjUQ1jM1inSwHRKTziZ6NAviRg1hd
    2v9+Yfepy5yuuHhQs38zgQKBgQC9TNBLWeuFb3BPA6KSDe6/HuDlrgvdamC3EPm0
    Amk+hHoEkuzlbw8N3+MzjvBCU7MYAy2JLWJaVFF4TLDV0UpYVk/hEeSeNmqnw0k5
    HDjmeTIOhguoICUZlXFxAmYsGYdiRqmDoFuXLjz3E6mtxCXQw2ZG0l2ED5mao7IW
    gxMM4QKBgQCDXJR/huZWwSpEHpsymsZsnd0lIqbdArI+wm5jqRGChF2AK+nTlWcM
    SDj5JgsxgchSaJb9JC3hW34cyKUt+gM6tplkFakRIf9UlrLD5xCYdXLLjXaUMAhn
    eIfcWV0Xz8NDdm6ww4/abMz5a5QTlavvTkDGXXQohesjCot65c0V+Q==
    -----END RSA PRIVATE KEY-----

  public-key: >
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0rsn7zFS7uUhYs/N91lr
    aHiZxjRZXjlKu8ZXHNKeXAOrnKCb4nxyM5cK+03Iwu+k+bEewQqKqXU/DiDrOT6U
    6YL9oTblpXDb6lyP3ksHS0KZxorVn34IcdSNS8RuSD0RFb2wFE6/lhQaBaneqiSB
    121a7xIRduAQBtRCqHjjSl/3KOViAiwWoK7q/UFcKVUPjnk1NqgDaKB1zeEtIxC3
    4O2c8ILg8kvHnGlcq4T4u6ISHiG+paxgLbDR8wuIb8nHzGb4lPCXsO84QpIwgRwO
    Fltaqsw2QudLEjdQjKMSaU7t0tqo/riGSVX/SPtSxmQb2aewD+dMebYQxxf1DXk7
    MQIDAQAB
    -----END PUBLIC KEY-----

